### ISSUE TITLE
Flux Infused Pickaxe mining level.

### ISSUE THREAD

**Issue by AnodeCathode** [bonii-xx/IguanaTweaksTConstruct#15] opened 2014-08-17 13:28 UTC
First time IguanaTweaks 2.0.1B2 is installed the Redstone Arsenal Flux Infused Pickaxe  shows a mining level of Cobalt and will break Obsidian but actually not break Cobalt. 

Restarting the client with no changes then shows the mining level as Redstone and it will then not break obsidian (or break it with no drop).

Deleting the config\IguanaTweaksTConstruct folder will then repeat this process. 

With: 
Forge 10.13.0.1206
IguanaTinkerTweaks-1.7.10-2.0.1B2
RedstoneArsenal-[1.7.10]1.1.0B3-8
TConstruct_mc1.7.10_1.6.0d38
TiC-Tooltips-mc1.7.10-1.1.9
CoFHCore-[1.7.10]3.0.0B3-26

**Comment by bonii-xx** [comment] 2014-08-17 20:27
Can't reproduce.the cobalt thing. However flux tools manage harvest levels a bit differently, that's why the general adaption doesn't work and it has redstone level instead of ardite level.
(The harvest level gets set, the tool just ignores it ;)) -> will be fixed

For the cobalt display.. were you playing client/server or SSP? If so, sounds like client and server had different configs. or cauldron.

**Comment by AnodeCathode** [comment] 2014-08-17 23:56
Interesting, the cobalt thing I was finding just in SSP. So not sure what was going on there. Thanks for the fix.

**Closed as completed** 2014-08-31 10:37 UTC
